### PR TITLE
Fix showing avatar empty space on accounts with ENS but no image attached

### LINKED ISSUE #824: Extra space for ENS names when there is no picture
image

This is the design:
image
Maybe whoever did this tasks was mistaken that the "100% transparent ENS" is when you have no ENS profile. Thats not the case. The top design is when there is not profile set

### PR DESCRIPTION
**Pull request by Diogomartf**
# Summary

Closes #824

This PR fixes showing extra empty space on accounts with ENS without image attached.

**Current**
image
**Old**
image

  # To Test

1. Open swapr app
	  - [ ] Connect to an ETH account with ENS and without avatar attached
	  - [ ] Check there isn't any empty space at the left.

### CODE REVIEW

**Comment by MilanVojnovic95** [comment]
Tested and looks ok to me 👍

**Comment by niemam29** [comment]
Looks good to me!

**Review by karczuRF — APPROVED** [review]

**Comment by kingalg** [comment]
Looks good to me as well! I have a question - @niemam29 @MilanVojnovic95 - when I'm impersonating a few people in a row for a second or two I can see avatar of previously impersonated person. Looks buggy/laggy. Did you saw something like this?

**Comment by Diogomartf** [comment]
> Looks good to me as well! I have a question - @niemam29 @MilanVojnovic95 - when I'm impersonating a few people in a row for a second or two I can see avatar of previously impersonated person. Looks buggy/laggy. Did you saw something like this?
> 
> 

I didn't test it impersonating a few people. I'll check and see if I can make it less buggy. 

Thanks for testing!

File: src/components/Web3Status/AccountStatus.tsx [hunk 1]
```diff
@@ -174,8 +174,9 @@ export function AccountStatus({
             </RowBetween>
           ) : ENSName ? (
             <>
-              {avatar && <Avatar url={avatar.image} />}
-              <>{ENSName}</>
+              {avatar?.image && <Avatar url={avatar.image} />}
+
```
Comment (adamazad) [inline src/components/Web3Status/AccountStatus.tsx:178]:
```suggestion
```

**Review by adamazad — CHANGES_REQUESTED** [review]
Look good!

**Review by adamazad — APPROVED** [review]

**Review by berteotti — APPROVED** [review]
