### PR TITLE
fix: add loading balances spacing

### LINKED ISSUE #744: Loading balance spacing
When balance is loading give the loading indicator and words(SWPR/ETH) spacing.

### PR DESCRIPTION
**Pull request by guerrap**
# Summary

Fixes #744 

Add right spacing for skeleton components inside the `Header` component.

before:
before

after:
after

  # To Test

1. Reload the page
- [ ] Verify the balance loaders in the header have a right margin

### CODE REVIEW

File: src/components/Header/index.tsx [hunk 1]
```diff
@@ -287,6 +287,10 @@ const StyledChevron = styled(ChevronUp)<{ isOpen: boolean }>`
   transform: ${({ isOpen }) => (isOpen ? 'rotate(0deg)' : 'rotate(180deg)')};
 `
 
+export const SpacedSkeleton = styled(Skeleton)`
+  margin-right: 3px;
+`
+
```
Comment (Mi-Lan) [inline src/components/Header/index.tsx:293]: I would suggest to move it inline styles like this style={{ marginRight: '3px' }} since its just used in 2 components. Or at least to place it is some different component if its being exported like this

Comment (guerrap) [reply src/components/Header/index.tsx]: Moved the style to inline margin

**Review by Mi-Lan — APPROVED** [review]
LGTM!

**Review by berteotti — APPROVED** [review]
👍

**Comment by niemam29** [comment]
Looks good for me
