### PR TITLE
fix: laggy input on swap

### LINKED ISSUE #1461: Problems with laggy input on swap page
**Description**
There are some problems when recalculating route for swap causing input to feel laggy 

#### Definition of done
- [X] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**Recording**

https://images.zenhubusercontent.com/209400598/dd4ec8c9-ec63-4f46-9068-837751bd57c2/s.mp4

### PR DESCRIPTION
**Pull request by berteotti**
# Summary

Fixes #1461

This PR solves the laggy input / trade result on swap page.

### CODE REVIEW

File: src/state/swap/hooks.ts [hunk 1]
```diff
@@ -258,11 +266,13 @@ export function useDerivedSwapInfo(platformOverride?: RoutablePlatform): UseDeri
...
-          setInputError(SWAP_INPUT_ERRORS.UNKNOWN)
-          setLoading(false)
-        })
+        if (error.name !== 'AbortError') {
+          console.error(error)
+          unstable_batchedUpdates(() => {
+            setInputError(SWAP_INPUT_ERRORS.UNKNOWN)
+            setLoading(false)
+          })
+        }
```
Comment (wixzi) [inline src/state/swap/hooks.ts:275]:
```suggestion
            setInputError(SWAP_INPUT_ERRORS.UNKNOWN)
            setLoading(false)
        }
```

we dont need this after react18

Comment (berteotti) [reply src/state/swap/hooks.ts:275]: Forgot to remove this. Thanks!

File: src/state/swap/hooks.ts [hunk 2]
```diff
@@ -314,15 +322,22 @@ export function useDerivedSwapInfo(platformOverride?: RoutablePlatform): UseDeri
...
-    staticJsonRpcProvider: StaticJsonRpcProvider | undefined
+    staticJsonRpcProvider: StaticJsonRpcProvider | undefined,
+    signal: AbortSignal
   ): Promise<EcoRouterResults> {
-    return isExactIn
+    const abortPromise = new Promise<EcoRouterResults>((resolve, reject) => {
+      signal.onabort = () => {
+        reject(new DOMException('Aborted', 'AbortError'))
+      }
+    })
```
Comment (wixzi) [inline src/state/swap/hooks.ts:338]: Do we need to log the Aborted message?

File: src/state/swap/hooks.ts [hunk 3]
```diff
@@ -341,6 +356,8 @@ export function useDerivedSwapInfo(platformOverride?: RoutablePlatform): UseDeri
           ecoRouterSourceOptionsParams,
           staticJsonRpcProvider
         )
+
+    return await Promise.race([abortPromise, ecoRouterPromise])
```
Comment (wixzi) [inline src/state/swap/hooks.ts:360]: Also you need to pass the signal down to the fetch request right?

**Comment by wixzi** [comment]
you can remove all unstable_batchedUpdates from the file

File: src/state/swap/hooks.ts [hunk 4]
```diff
@@ -179,6 +181,11 @@ export function useDerivedSwapInfo(platformOverride?: RoutablePlatform): UseDeri
   useEffect(() => {
     const [inputCurrencyBalance] = relevantTokenBalances
 
+    // Abort previous controller and create new one
```
Comment (Diogomartf) [inline src/state/swap/hooks.ts:184]: this should be replaced with a function, with a descriptive name and then we can remove the comment

Comment (Diogomartf) [inline src/state/swap/hooks.ts:184]: this should be replaced with a function with a descriptive name and then we can remove the comment

**Comment by Diogomartf** [comment]
wow, such a nice fix! Much more responsive. Great job 👏

File: src/state/swap/hooks.ts (hunk 2 above)
Comment (berteotti) [reply src/state/swap/hooks.ts:329]: We can also call `resolve()` and check if the are no trades. But I think it's better to throw an error and check for the message, because the promise wasn't successful.

File: src/hooks/useAbortController.ts [hunk 5]
```diff
@@ -0,0 +1,17 @@
...
+    if (abortControllerRef.current) {
+      abortControllerRef.current.abort()
+    }
+
+    abortControllerRef.current = new AbortController()
+
+    return abortControllerRef.current.signal
+  }, [])
+
+  return { abortControllerSignal }
```
Comment (wixzi) [inline src/hooks/useAbortController.ts:16]:
```suggestion
  return abortSignal
```

File: src/state/swap/hooks.ts [hunk 6]
```diff
@@ -153,6 +154,7 @@ export function useDerivedSwapInfo(platformOverride?: RoutablePlatform): UseDeri
 
   const [isQuoteExpired, setIsQuoteExpired] = useState(false)
   const quoteExpiryTimeout = useRef<NodeJS.Timeout>()
+  const { abortControllerSignal } = useAbortController()
```
Comment (wixzi) [inline src/state/swap/hooks.ts:157]:
```suggestion
  const abortSignal = useAbortController()
```

File: src/hooks/useAbortController.ts [hunk 7]
```diff
@@ -0,0 +1,17 @@
...
+}
```
Comment (wixzi) [inline src/hooks/useAbortController.ts:17]: Good job @berteotti . Suggest some minor variable name changes. If you feel its ok you can ignore.

```suggestion
export function useAbortController() {
  const abortControllerRef = useRef<AbortController>()

  const getAbortSignal = useCallback(() => {
    if (abortControllerRef.current) {
      abortControllerRef.current.abort()
    }
    abortControllerRef.current = new AbortController()
    return abortControllerRef.current.signal
  }, [])

  return getAbortSignal
}
```

File: src/state/swap/hooks.ts (hunk 6 above)
Comment (wixzi) [inline src/state/swap/hooks.ts:157]:
```suggestion
  const getAbortSignal = useAbortController()
```

File: src/state/swap/hooks.ts [hunk 8]
```diff
@@ -179,6 +181,8 @@ export function useDerivedSwapInfo(platformOverride?: RoutablePlatform): UseDeri
   useEffect(() => {
     const [inputCurrencyBalance] = relevantTokenBalances
 
+    const signal = abortControllerSignal()
```
Comment (wixzi) [inline src/state/swap/hooks.ts:184]:
```suggestion
    const signal = getAbortSignal()
```

File: src/state/swap/hooks.ts [hunk 9]
```diff
@@ -314,15 +313,22 @@ export function useDerivedSwapInfo(platformOverride?: RoutablePlatform): UseDeri
...
     inputCurrency: Currency,
     outputCurrency: Currency,
     commonParams: { maximumSlippage: Percent; receiver: string; user: string },
     ecoRouterSourceOptionsParams: { uniswapV2: { useMultihops: boolean } },
-    staticJsonRpcProvider: StaticJsonRpcProvider | undefined
+    staticJsonRpcProvider: StaticJsonRpcProvider | undefined,
+    signal: AbortSignal
   ): Promise<EcoRouterResults> {
-    return isExactIn
+    const abortPromise = new Promise<EcoRouterResults>((resolve, reject) => {
```
Comment (wixzi) [inline src/state/swap/hooks.ts:325]:
```suggestion
    const abortPromise = new Promise<EcoRouterResults>((_, reject) => {
```

**Review by wixzi — APPROVED** [review]
LGTM 🥇

**Comment by wixzi** [comment]
Remove the warnings in eslint and `build` and `netlify` will pass.

**Review by mix1o — APPROVED** [review]

**Comment by 0xVenky** [comment]
Hey, can we fix a deploy preview for this build? Tested it locally, but would prefer to test it once on a production build. It looks much faster and would be good to get it in Beta 16 if possible :)

**Comment by wixzi** [comment]
> https://deploy-preview-1486--swapr.netlify.app/

@0xVenky Fixed netlify build

**Comment by 0xVenky** [comment]
LGTM! Lets merge it!  :) 🚀
