### PR TITLE
Fix pending transaction sorting

### LINKED ISSUE #1479: Pending items to be listed at the top of user dashboard
**Description**
Seems like we have messed the sorting logic here. Would be good to display the pending transactions at the top and then all the other transaction statuses.

Right now, it feels liek it is first sorted based on Transaction type and then on timestamp. It should be the following way:
Sort desc based on transaction status (Pending at the top and Collect / Claim next and then all the completed and cancelled oens), then sort it based on timestamp.

image

### PR DESCRIPTION
**Pull request by wixzi**
# Summary

Fixes #1479

Fix pending transaction sorting

  # To Test

Pending transactions should appear at the top of the list

  # Background

Screenshot 2022-09-13 at 22 30 14

### CODE REVIEW

**Comment by wixzi** [comment]
Make ACTIVE and ENDED to center align

Screenshot 2022-09-14 at 09 36 54
Screenshot 2022-09-14 at 09 36 59

After:
Screenshot 2022-09-14 at 09 37 32
Screenshot 2022-09-14 at 09 37 36

**Comment by wixzi** [comment]
@0xVenky @MilanVojnovic95 Can you test this for the bug #1479 ?

**Review by niemam29 — APPROVED** [review]
Tested and looks good to me

**Comment by 0xVenky** [comment]
Looks good to me! I will ask for one code review and then we should be good to merge

**Review by mix1o — APPROVED** [review]

File: src/pages/Account/TransactionRows/SwapTransactionRow.tsx [hunk 1]
```diff
@@ -85,10 +85,11 @@ export function SwapTransactionRow({ transaction }: SwapTransactionRowProps) {
...
 
       <TransactionDetails>
-        {confirmedTime ? (
+        {confirmedTime ?? addedTime ? (
           <Flex flexDirection="column" fontSize="12px">
-            <Box>{DateTime.fromMillis(confirmedTime).toFormat('HH:mm:ss')}</Box>
-            <Box>{DateTime.fromMillis(confirmedTime).toFormat('dd/MM/yyyy')}</Box>
+            <Box>{DateTime.fromMillis(confirmedTime ?? addedTime).toFormat('HH:mm:ss')}</Box>
+            <Box>{DateTime.fromMillis(confirmedTime ?? addedTime).toFormat('dd/MM/yyyy')}</Box>
+            {!confirmedTime && <Box fontSize="8px">( ADDED TIME )</Box>}
```
Comment (Diogomartf) [inline src/pages/Account/TransactionRows/SwapTransactionRow.tsx:92]: This looks a bit odd, why "added time" in uppercase?  Couldn't see how it looks on the preview if you have screenshot it would be great.

Also it should be a translated.

File: src/pages/Account/TransactionRows/TransactionHeaders.tsx [hunk 2]
```diff
@@ -16,7 +16,7 @@ export function TransactionHeaders() {
           <TransactionDetails justifyContent="start">Price</TransactionDetails>
           <TransactionDetails>Type</TransactionDetails>
           <TransactionDetails>Status</TransactionDetails>
-          <TransactionDetails>Time</TransactionDetails>
+          <TransactionDetails>Confirmed Time</TransactionDetails>
```
Comment (Diogomartf) [inline src/pages/Account/TransactionRows/TransactionHeaders.tsx:19]: We should use translations here.

File: src/pages/Account/TransactionRows/SwapTransactionRow.tsx (hunk 1 above)
Comment (wixzi) [reply src/pages/Account/TransactionRows/SwapTransactionRow.tsx:92]: Screenshot 2022-09-14 at 20 40 06
It was upper case by css. So I added it as uppercase

File: src/pages/Account/TransactionRows/TransactionHeaders.tsx (hunk 2 above)
Comment (wixzi) [reply src/pages/Account/TransactionRows/TransactionHeaders.tsx]: Yes moved to translations
