### PR TITLE
Bugfix/926 hide unwanted single token staking loading indicator

### LINKED ISSUE #926: Loading indicator on single token staking
**Description**
There is a loading indicator that keeps going on and on, trying to figure out what the other token is I believe. We should not have this loading indicator on single token staking.

#### Definition of done
- [x] Description is created (Task creator)
- [x] Code is complete (Developer)
- [x] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [x] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce** 

Goto https://swapr.eth.limo/#/rewards/0x532801ED6f82FFfD2DAB70A19fC2d7B2772C4f4b/0xD3C1ed9ABb4358bAc2C92229B5b950D1Ff0112df/singleSidedStaking?chainId=100

Look for the loading indicator next to SWPR icon.

image

**Expected behavior**
The loading indicator should not be there.

### PR DESCRIPTION
**Pull request by wixzi**
# Summary

Fixes #926

Single staked campaign was showing loader for the second token. Since its only one token we dont want that loading.

Screenshot 2022-05-06 at 12 08 46

  # To Test

Go to rewards => swapr and should not see any loading.

  # Background

Updated tsconfig and eslint 

1. Unused variables shouldn't shop compilation, its bad developer experience since we cant comment some file for testing.
2. Should be able to ignore unused vars with _ , its useful when we want to destructure out some props
eg: `{id: _unwanted, ...rest}` and then use the rest
3. Also `@typescript-eslint/no-non-null-assertion` so can do non-null assertion with `!` if we are sure it will not be null.

### CODE REVIEW

**Comment by MilanVojnovic95** [comment]
Tested and looks ok to me. 👍

**Comment by kingalg** [comment]
Looks fine.

File: src/components/Header/index.tsx [hunk 1]
```diff
@@ -261,7 +261,7 @@ function Header() {
         newSwprBalance={newSwprBalance}
         stakedAmount={stakedTokenAmount?.toFixed(3)}
         singleSidedCampaignLink={
-          data && !loading ? `/rewards/${data.stakeToken.address}/${data.address}/singleSidedStaking` : undefined
+          data && !loading ? `/rewards/single-campaign/${data.stakeToken.address}/${data.address}` : undefined
```
Comment (adamazad) [inline src/components/Header/index.tsx:264]: This makes more sense. Should we consider adding a redirect from old pages to new ones?

File: tsconfig.json [hunk 2]
```diff
@@ -11,7 +11,6 @@
     "strict": true,
     "alwaysStrict": true,
     "strictNullChecks": true,
-    "noUnusedLocals": true,
```
[the remark this answers is not in the document]
Comment (adamazad) [reply tsconfig.json:14]: I think we should keep this. There are times when a module is imported and increases bundle size.

File: src/pages/App.tsx [hunk 3]
```diff
@@ -119,17 +119,17 @@ export default function App() {
...
-                    path="/rewards/:currencyIdA/:liquidityMiningCampaignId/singleSidedStaking"
+                    path="/rewards/single-campaign/:currencyIdA/:liquidityMiningCampaignId"
                     component={LiquidityMiningCampaign}
                   />
-                  <FullFeaturesRoute exact strict path="/pools/:currencyIdA/:currencyIdB" component={Pair} />
                   <FullFeaturesRoute
                     exact
                     strict
-                    path="/rewards/:currencyIdA/:currencyIdB/:liquidityMiningCampaignId"
+                    path="/rewards/campaign/:currencyIdA/:currencyIdB/:liquidityMiningCampaignId"
```
Comment (adamazad) [inline src/pages/App.tsx:132]: Good! Maybe `single-sided-campaign`? @0xVenky can chime on this.

**Review by adamazad — COMMENTED** [review]
Great job at pointing out the camel cases in the URL

File: src/components/Header/index.tsx (hunk 1 above)
Comment (wixzi) [reply src/components/Header/index.tsx:264]: old routes are little buggy since it matches campaign also since the last part is dynamic. Are you concerned about someone has bookmarked it?

Comment (wixzi) [reply src/components/Header/index.tsx:264]: But old routes will redirect them back to rewards since it doesn't match any routes

File: src/pages/App.tsx (hunk 3 above)
Comment (wixzi) [reply src/pages/App.tsx:132]: Yes I can change to `single-sided-campaign` its more accurate, I was trying to make it short 😄

**Review by adamazad — APPROVED** [review]
Nice! Just a side challenge for you if you dig into this deeper. I am certain we can remove `token0.address/token1.address` from campaigns. All relevant information regarding the staking pair tokens is available in the subgraph. I was not involved in the design choices of farming campaigns, but I wouldn't have put that information in the URL.

**Comment by 0xVenky** [comment]
> Nice! Just a side challenge for you if you dig into this deeper. I am certain we can remove `token0.address/token1.address` from campaigns. All relevant information regarding the staking pair tokens is available in the subgraph. I was not involved in the design choices of farming campaigns, but I wouldn't have put that information in the URL.

Going to merge this PR. If you wish to accept this challenge, lets have a new ticket created 😬
