### PR TITLE
Show eth balance only when wallet connected

### LINKED ISSUE #812: Ethereum balance should be only displayed when user have connected wallet
**Description**
Ethereum balance should be only displayed when user have connected wallet just as stake balance.

**How to Reproduce**
1. Open Swapr without connected wallet

**Expected behavior**
Neither stake or balance is displayed

**Screenshots**

### PR DESCRIPTION
**Pull request by karczuRF**
# Summary

Fixes #812 

Show account balance only when user's wallet is connected. The same as gas on Gnosis Chain.

image
 

  # To Test

1. Open the swapr app
- [ ] Wallet is disconnected - button shows "connect wallet"
- [ ] Account balance is not visible 

2. Switch network to Gnosis Chain
- [ ] Account balance is not visible 
- [ ] Gas icon is not visible 

3. Connect wallet to any network
- [ ] Account balance is visible 
- [ ] 'SWPR' balance is visible

image

4. Connect wallet to Gnosis Chain
- [ ] Account balance is visible 
- [ ] 'SWPR' balance is visible
- [ ] gas icon is visible and show options if clicked

image

### CODE REVIEW

**Review by niemam29 — APPROVED** [review]
Looks good for me!

File: src/components/Header/index.tsx [hunk 1]
```diff
@@ -383,7 +383,7 @@ function Header() {
             {isUnsupportedChainIdError ? (
```
Comment (mix1o) [inline src/components/Header/index.tsx:383]: I think you can reduce this code to something like that
image

**Review by mix1o — APPROVED** [review]
