### PR TITLE
[fix] Handle error when it fails to fetch a subgraph on landing page stats

### LINKED ISSUE #795: Implement error handing for the Landing Page components
**Description**
When graph is down app crashes in Stats.js component I think we should look into implementing error catchers for all non essential parts in LandingPageComponents folder
**How to Reproduce**
I will give example for just Stats.js folder but should be checked for all LandingPageComponents
1. Go to src/components/LandingPageComponents/Stats.js
2. fuck up one of the apiUrlList(also they should be imported from the clients.js folder) url-s by for example on xdai removing one letter
3. Refresh the page

**Screenshots**
This is error  Im seeing  even on page refresh
Screenshot 2022-03-21 at 14 16 22
Screenshot 2022-03-21 at 14 24 43

### PR DESCRIPTION
**Pull request by Diogomartf**
Also imported API urls from `client.ts`

# Summary

Fixes #795

Handle errors when fetching stats from subgraphs on the landing page.

**Now**
If there is an error fetching a subgraph we show "not updated" bellow stats.

image

**Previously** 
eg. when a subgraph was down the page broke and showed this error.

image

  # To Test
We can only test if it fails to fetch from subgraph.

1. Open landing page
  - [ ] The page doesn't break with the fetch error
  - [ ] If it fails to fetch some data from a subgraph it shows "not update" bellow the tittle

### CODE REVIEW

File: src/components/LandingPageComponents/Stats.js [hunk 1]
```diff
@@ -1,490 +1,465 @@
...
-}`;
-
+}`
 
-const retrieveData = async (url) => {
+const retrieveData = async url => {
+  const client = new ApolloClient({
+    uri: url,
+    cache: new InMemoryCache()
+  })
```
Comment (adamazad) [inline src/components/LandingPageComponents/Stats.js:30]: This client is created every time `retrieveData` is invoked. Hence, there's no caching really. You can move it up.

File: src/components/LandingPageComponents/Stats.js [hunk 2]
```diff
@@ -1,490 +1,465 @@
...
-    }, []);
+  useEffect(() => {
+    const tvlPromise = fetch('https://api.llama.fi/tvl/swapr')
+    tvlPromise
+      .then(data => {
+        return data.json()
+      })
+      .then(decodedTvl => {
+        setTvl((decodedTvl / 1000000).toFixed(1))
+      })
```
Comment (adamazad) [inline src/components/LandingPageComponents/Stats.js:61]: Fetch throws an error on network errors.

File: src/components/LandingPageComponents/Stats.js [hunk 3]
```diff
@@ -1,490 +1,465 @@
...
+    })
+    swaprPricePromise
+      .then(data => {
+        return data.json()
+      })
+      .then(decodedPrice => {
+        const swaprPrice = decodedPrice.coins[coinCode].price.toFixed(3).toString()
+        setSwaprPrice(swaprPrice)
+      })
```
Comment (adamazad) [inline src/components/LandingPageComponents/Stats.js:79]: Same as above comment.

File: src/components/LandingPageComponents/Stats.js [hunk 4]
```diff
@@ -1,490 +1,465 @@
...
-            retrieveData(apiUrlList[val]).then((data) => {
-                let floatTx = parseFloat(data.data.swaprFactories[0].txCount);
-                let floatVolume = parseFloat(data.data.swaprFactories[0].totalVolumeUSD);
+  useEffect(() => {
+    for (const apiUrl in apiUrlList) {
+      // eslint-disable-next-line
+      retrieveData(apiUrlList[apiUrl]).then(data => {
+        if (data) {
+          let floatTx = parseFloat(data.data.swaprFactories[0].txCount)
+          let floatVolume = parseFloat(data.data.swaprFactories[0].totalVolumeUSD)
```
Comment (adamazad) [inline src/components/LandingPageComponents/Stats.js:88]: Best to create to import the immediate subgraph clients from the source. Caching probably won't make sense here.

**Review by adamazad — CHANGES_REQUESTED** [review]

File: src/components/LandingPageComponents/Stats.js [hunk 5]
```diff
@@ -1,490 +1,465 @@
...
-        .then((data) => {
-            // console.log('Subgraph data: ', data)
-            return data;
-        })
-        .catch((err) => {
-            console.log('Error fetching data: ', err);
-            return err;
-        });
-    return asyncClient;
+  const asyncClient = await client
```
Comment (adamazad) [inline src/components/LandingPageComponents/Stats.js:32]: The variable name is not descriptive. Just return the promise.

**Review by adamazad — CHANGES_REQUESTED** [review]

File: src/components/LandingPageComponents/Stats.js (hunk 5 above)
Comment (Diogomartf) [reply src/components/LandingPageComponents/Stats.js:32]: Yup, makes sense.

File: src/components/LandingPageComponents/Stats.js (hunk 1 above)
Comment (Diogomartf) [reply src/components/LandingPageComponents/Stats.js:30]: Yup. This makes a lot of sense. Thank you Adam. I'll fix it.

File: src/components/LandingPageComponents/Stats.js (hunk 2 above)
Comment (Diogomartf) [reply src/components/LandingPageComponents/Stats.js:61]: I'll check this out.

File: src/components/LandingPageComponents/Stats.js (hunk 4 above)
Comment (Diogomartf) [reply src/components/LandingPageComponents/Stats.js:88]: Ok, what you are saying is to use `immediateSubgraphClients` instead of `subgraphClients` right?

So we use the `subgraphClients` to leverage caching? And the other in more simple cases?

I'll read more about Apollo client to understand this part of the system. If have any reading suggestions I appreciate that.

Comment (Diogomartf) [reply src/components/LandingPageComponents/Stats.js:88]: Ok, I imported and replaced the local client, so we use `immediateSubgraphClients` directly instead of building an Apollo Client.

File: src/components/LandingPageComponents/Stats.js [hunk 6]
```diff
@@ -1,490 +1,464 @@
...
+    swaprPricePromise
+      .then(data => {
+        return data.json()
+      })
+      .then(decodedPrice => {
+        const swaprPrice = decodedPrice.coins[coinCode].price.toFixed(3).toString()
+        setSwaprPrice(swaprPrice)
+      })
+      .catch(err => {
+        console.log('Error fetching data: ', err)
```
Comment (berteotti) [inline src/components/LandingPageComponents/Stats.js:78]: I think this is clearer

```suggestion
        console.error('Error fetching Swapr price: ', err)
```

File: src/components/LandingPageComponents/Stats.js [hunk 7]
```diff
@@ -1,490 +1,464 @@
...
+    const tvlPromise = fetch('https://api.llama.fi/tvl/swapr')
+    tvlPromise
+      .then(data => {
+        return data.json()
+      })
+      .then(decodedTvl => {
+        setTvl((decodedTvl / 1000000).toFixed(1))
+      })
+      .catch(err => {
+        console.log('Error fetching data: ', err)
```
Comment (berteotti) [inline src/components/LandingPageComponents/Stats.js:57]: I think this is clearer

```suggestion
        console.error('Error fetching Swapr TVL: ', err)
```

Comment (Diogomartf) [reply src/components/LandingPageComponents/Stats.js:57]: I'll change it. Thanks.

File: src/components/LandingPageComponents/Stats.js (hunk 6 above)
Comment (Diogomartf) [reply src/components/LandingPageComponents/Stats.js:78]: I'll change it. Thanks.
