### PR TITLE
fix: incorrect rounded value of tokens in balance

### LINKED ISSUE #1031: Incorrect rounded value of tokens in Swap modal
**Description**
There is some problem which makes last digit of token value rounded to zero in some cases 

#### Definition of done
- [X] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**Screenshots**

### PR DESCRIPTION
**Pull request by berteotti**
# Summary

Fixes #1031

Fix incorrect rounded value of tokens when balance is too large

image

  # To Test

1. Open the page `swap`
2. Choose a token with large balance
- [ ] Verify if full token balance appears with decimal places

### CODE REVIEW

File: src/components/CurrencyInputPanel/CurrencyUserBalance.tsx [hunk 1]
```diff
@@ -21,7 +23,11 @@ export const CurrencyUserBalance = ({
 
   if (!account) return null
 
-  const trimmedBalance: string = limitNumberOfDecimalPlaces(balance || selectedCurrencyBalance) || '0'
+  const availableBalance = balance || selectedCurrencyBalance
```
Comment (Diogomartf) [inline src/components/CurrencyInputPanel/CurrencyUserBalance.tsx:26]: cool 😎

**Review by Diogomartf — APPROVED** [review]

**Comment by niemam29** [comment]
Looks good, but i just have noticed that this problem also occur in token picker 

cach2

cache3

**Comment by berteotti** [comment]
Will close this PR as there will be a new token picker UI.

**Comment by berteotti** [comment]
> cache3

@niemam29 There will be a new token picker UI so I don't think it's relevant to solve this right now.

**Review by jorgedclopes — APPROVED** [review]
