### PR TITLE
fix: show is loading state when wallet is disconnected

### LINKED ISSUE #1188: Swapbox stops loading when wallet is disconnected
**Description**
Swapbox stops loading when wallet is disconnected but shows trading options in the end.

#### Definition of done
- [ ] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**
1. Go to swap
2. Simulate a trade without connecting wallet

**Expected behavior**
Swapbox should load even when wallet is disconnected

### PR DESCRIPTION
**Pull request by berteotti**
# Summary

Fixes #1188

Show is loading state when wallet is disconnected. Also improved how we handle swap input errors.

  # To Test

1. Open the page `swap`
2. Simulate a trade without connecting wallet
- [ ] Swapbox should start loading

### CODE REVIEW

File: src/components/swap/SwapButtons/SwapButton.tsx [hunk 1]
```diff
@@ -48,25 +49,36 @@ const StyledPlataformText = styled(Text)`
...
   const { t } = useTranslation()
 
+  const SWAP_INPUT_ERRORS_MESSAGE = {
+    [SWAP_INPUT_ERRORS.CONNECT_WALLET]: 'Connect wallet',
+    [SWAP_INPUT_ERRORS.ENTER_AMOUNT]: 'Enter amount',
+    [SWAP_INPUT_ERRORS.SELECT_TOKEN]: 'Select token',
+    [SWAP_INPUT_ERRORS.ENTER_RECIPIENT]: 'Enter recipient',
+    [SWAP_INPUT_ERRORS.INVALID_RECIPIENT]: 'Invalid recipient',
+    [SWAP_INPUT_ERRORS.INSUFFICIENT_BALANCE]: `Insufficient ${amountInCurrencySymbol} balance`,
+  }
```
Comment (adamazad) [inline src/components/swap/SwapButtons/SwapButton.tsx:75]: Nice structure, better to reason about things :)

**Review by adamazad — APPROVED** [review]

**Review by wixzi — APPROVED** [review]

File: src/components/swap/SwapButtons/SwapButton.tsx (hunk 1 above)
Comment (berteotti) [reply src/components/swap/SwapButtons/SwapButton.tsx:75]: Will add translations soon!
