### PR TITLE
hotfix: Fix pool page from breaking and shows 24h volume on Arbitrum

### LINKED ISSUE #1577: Pools page not showing 24h volume on Arbitrum (and breaking)
**Description**
Liquidity pools on Arbitrum are not showing value for 24h volume and the page breaks after a while.

#### Definition of done
- [ ] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**How to Reproduce**
1. Switch to arbitrum
2. Go to /pools
3. No 24h volume data
4. stay for a while (couple of minutes)
5. Page breaks

**Expected behavior**
Should not break and show the correct values.

**Screenshots**
image

### PR DESCRIPTION
**Pull request by Diogomartf**
# Summary

This PR fixes the page breaking and showing 24h volume. 

fixes #1577

image

  # To Test

1. <<Step one>> Open the page `about`
- [ ] <<What to expect?>> Verify it contains about information...
- [ ] Checkbox Style list of things a QA person could verify, i.e.
- [ ] Should display Text Input our storybook
- [ ] Input should not accept Numbers
2. <<Step two>> ...

  # Background

*Optional: Give background information for changes you've made, that might be difficult to explain via comments*

### CODE REVIEW

**Review by adamazad — APPROVED** [review]

**Comment by adamazad** [comment]
Let's merge this ASAP @berteotti

File: src/hooks/usePairVolume24hUSD.ts [hunk 1]
```diff
@@ -13,7 +13,7 @@ import { SWPRSupportedChains } from '../utils/chainSupportsSWPR'
 
 const GET_BLOCK_BY_TIMESTAMP = gql`
   query getBlockFromTimestamp($timestamp: String!) {
-    blocks(first: 10, orderBy: number, orderDirection: asc, where: { timestamp_gt: $timestamp }) {
+    blocks(first: 999, orderBy: number, orderDirection: asc, where: { timestamp_gt: $timestamp }) {
```
Comment (berteotti) [inline src/hooks/usePairVolume24hUSD.ts:16]: This solution seems to fetch subgraph data but don't know why! @adamazad any idea? Also does it look good to you?

**Review by berteotti — APPROVED** [review]
Looks good to me now
