### PR TITLE
Fix: 1344 add spacing for the text in swap button 

### LINKED ISSUE #1344: Lack of whitespace in swap button on expert mode
**Description**
There is no whitespace between exchange and anyway in swap button on expert mode

#### Definition of done
- [x] Description is created (Task creator)
- [x] Code is complete (Developer)
- [x] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**Screenshots**

### PR DESCRIPTION
**Pull request by mwiniarsk**
# Summary

Fixes #1344

Add spacing for the text in the swap button and set the smaller font to fit the mobile design

Selection_191

  # To Test

1. Go to the swap page
2. Select tokens on expert mode to have a high price impact
3. Check the design, also on mobile

### CODE REVIEW

File: src/components/swap/SwapButtons/SwapButton.tsx [hunk 1]
```diff
@@ -105,11 +126,11 @@ export const SwapButton = ({
                   height={21}
                 />
                 <Box marginLeft={2}>
-                  <StyledPlataformText>{ROUTABLE_PLATFORM_STYLE[platformName].name}</StyledPlataformText>
+                  <StyledPlatformText>{ROUTABLE_PLATFORM_STYLE[platformName].name}</StyledPlatformText>
                 </Box>
               </Flex>
             )}
-            {priceImpactSeverity > PRICE_IMPACT_MEDIUM && ` ${t('button.anyway')}`}
+            <AnywayText>{priceImpactSeverity > PRICE_IMPACT_MEDIUM && t('button.anyway')}</AnywayText>
```
Comment (Diogomartf) [inline src/components/swap/SwapButtons/SwapButton.tsx:133]: Maybe we can use `UnifiedText`  here and add Box with margin left.

```suggestion
	<Box marginLeft={"0.25rem"}>
           <UnifiedText>{priceImpactSeverity > PRICE_IMPACT_MEDIUM && t('button.anyway')}</AnywayText>
         </Box>
```

**Comment by niemam29** [comment]
To be pixel perfect the interval here should be 10 i believe. 

cach2

File: src/components/swap/SwapButtons/SwapButton.tsx (hunk 1 above)
Comment (mwiniarsk) [reply src/components/swap/SwapButtons/SwapButton.tsx:133]: I would prefer to add one more styled component than add one more div to DOM, as the page is working slower. I know that it is insignificant in this case, but it makes a difference on a larger scale

**Comment by mwiniarsk** [comment]
> To be pixel perfect the interval here should be 10 i believe.
> 
> cach2

it should be fixed now

File: src/components/swap/SwapButtons/SwapButton.tsx [hunk 2]
```diff
@@ -52,9 +56,27 @@ const LogoWithText = styled.div`
...
+const UnifyFontSize = css`
   font-size: 15px;
+
+  ${({ theme }) => theme.mediaWidth.upToExtraSmall`
+    font-size: 13px;
+  `};
+`
+
+const StyledPlatformText = styled.div`
+  text-transform: none;
```
Comment (adamazad) [inline src/components/swap/SwapButtons/SwapButton.tsx:68]: I think we should use uppercase to avoid:

image

Comment (mwiniarsk) [reply src/components/swap/SwapButtons/SwapButton.tsx:68]: It was like that before, so up to you guys

**Review by Diogomartf — APPROVED** [review]

File: src/components/swap/SwapButtons/SwapButton.tsx (hunk 2 above)
Comment (adamazad) [reply src/components/swap/SwapButtons/SwapButton.tsx:68]: I prefer upper case.
