### PR TITLE
Fix: Display swap button above error message in expert mode

### LINKED ISSUE #1068: When rejecting transaction on gnosis network in expert mode swap button is hidden behind "transaction rejected" message
**Description**
When rejecting transaction in expert mode swap button is hidden behind "transaction rejected" message. 

#### Definition of done
- [X] Description is created (Task creator)
- [ ] Code is complete (Developer)
- [ ] Scope of test and what was done section is defined in task (Developer)
- [ ] Review passed (Code reviewer)
- [ ] Verified manually (QA)
- [ ] Test cases created/updated if necessary (QA)
- [ ] Change successfully merged
- [ ] Release notes added if needed

**Screenshots**

### PR DESCRIPTION
**Pull request by mwiniarsk**
# Summary

Fixes #1068 

Display the swap button above an error message in expert mode

Selection_173

UPDATE:
I need to pass to the error component prop to identify which variant should we display

Selection_174

  # To Test

1. Open the swap page
2. Start transaction
3. Reject transaction
4. Swap button should be displayed

### CODE REVIEW

**Review by mix1o — APPROVED** [review]

**Review by karczuRF — APPROVED** [review]

**Comment by niemam29** [comment]
Tested and looks good to me!

File: src/components/swap/SwapButtons/SwapButtons.tsx [hunk 1]
```diff
@@ -146,6 +146,12 @@ export function SwapButtons({
     )
   }
 
+  const errorBox = (isSpaceAtTop = true) => (
+    <>
+      {isExpertMode && swapErrorMessage && <SwapCallbackError isSpaceAtTop={isSpaceAtTop} error={swapErrorMessage} />}
+    </>
+  )
+
```
Comment (wixzi) [inline src/components/swap/SwapButtons/SwapButtons.tsx:154]: Its not a good practice to create components inside functional components. I suggest you to create it outside and pass it as props


```
 const ErrorBox = ({isSpaceAtTop, isExpertMode, swapErrorMessage}) => (
    <>
      {isExpertMode && swapErrorMessage && <SwapCallbackError isSpaceAtTop={isSpaceAtTop ?? true} error={swapErrorMessage} />}
    </>
  )
  
  ```

Comment (adamazad) [reply src/components/swap/SwapButtons/SwapButtons.tsx:154]: Same comment :)

**Review by adamazad — APPROVED** [review]

File: src/components/swap/SwapButtons/SwapButtons.tsx [hunk 2]
```diff
@@ -46,6 +46,18 @@ interface SwapButtonsProps {
   setWrapState: ((wrapState: WrapState) => void) | undefined
 }
 
+const errorBox = ({
```
Comment (adamazad) [inline src/components/swap/SwapButtons/SwapButtons.tsx:49]: This is a component. Makes sense to use the title case. Besides that, I will make `swapErrorMessage` a required prop :)

**Review by adamazad — CHANGES_REQUESTED** [review]

File: src/components/swap/SwapButtons/SwapButtons.tsx (hunk 2 above)
Comment (mwiniarsk) [reply src/components/swap/SwapButtons/SwapButtons.tsx:49]: yup, true, it is a component. What do you mean by the title case?

Comment (adamazad) [reply src/components/swap/SwapButtons/SwapButtons.tsx:49]: `ErrorBox` :)

Comment (mwiniarsk) [reply src/components/swap/SwapButtons/SwapButtons.tsx:49]: ok, you mean to rename it as ErrorBox! :D

Comment (mwiniarsk) [reply src/components/swap/SwapButtons/SwapButtons.tsx]: Renamed, moved to a separate file, and leave prop `swapErrorMessage` as a string or undefined, and both cases as undefined or empty string are handled. If it will be always a required prop so we can easily change it.

File: src/components/swap/SwapButtons/SwapButtons.tsx [hunk 3]
```diff
@@ -186,24 +186,24 @@ export function SwapButtons({
...
+        onClick={onSwapClick}
+        id="swap-button"
+        disabled={!isValid || (priceImpactSeverity > 3 && !isExpertMode) || !!swapCallbackError}
+        platformName={trade?.platform.name}
+        swapInputError={swapInputError}
+        priceImpactSeverity={priceImpactSeverity}
+        isExpertMode={isExpertMode}
+        amountInCurrencySymbol={currencies[Field.INPUT]?.symbol}
+      />
+      {ErrorBox({ isExpertMode, swapErrorMessage, isSpaceAtTop: false })}
```
Comment (adamazad) [inline src/components/swap/SwapButtons/SwapButtons.tsx:206]: I like this!

**Review by adamazad — APPROVED** [review]

**Comment by niemam29** [comment]
Retested and looks good!
